version: "3.8"
services:
#  web:
#    build: .
#    container_name: confour
#    ports:
#      - '3000:3000'
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#      - WATCHPACK_POLLING=true
#    volumes:
#      - .:/app
#      - /app/node_modules # Ensure not deleted
#    stdin_open: true
#    tty: true
  test:
    build: .
    container_name: confour-test
    environment:
      - NODE_ENV=test
    volumes:
      - .:/app
      - /app/node_modules
#    command: q